<?php

namespace GameBundle\Repository;

/**
 * MoviemonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MoviemonRepository extends \Doctrine\ORM\EntityRepository
{
}
